services:
  redis:
    container_name: beyond-redis
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - server

  postgres:
    container_name: beyond-postgres
    image: "postgres:alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=beyond
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - server

volumes:
  cache:
  pgdb:

networks:
  server:
    driver: bridge
